name: flutter_clean_architecture
description: A Flutter project for assessment purpose.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_svg: 1.1.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.17
  rxdart: ^0.27.7
  mockito: ^5.3.2
  bloc_test: ^9.1.1
  mocktail: ^0.3.0
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
